### ISSUE TITLE
pg. 430,431: FIFO Azure Queues/Service Bus compared-contrasted

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#1]
Confusing language:
Pages 430 & 431, the topic is Azure Queues --the content is ambiguous. Two individual paragraphs discuss FIFO processing but the paragraph on pg. 430  states that Azure Queues _does not support_ FIFO usage. On pg. 431 we find: "... is used to _enforce_ FIFO processing of Azure Queue messages." So a contradiction. I believe "does not guarantee FIFO usage" might be better terminology. Mentioning that Service Bus Queues do guarantee FIFO might be useful as well.
Reference: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted#additional-information.

**Comment by benperk** [comment]
The sentence on page 430 - "This most commonly referred to as first in, first out (FIFO), something that Azure Queues does not support." should be changed to something like "..., something which Azure Queues does not support **by default**."  Service Bus does not support FIFO by default either, you will need to make some rather advanced configurations to implement something like that.  With some modifications you could get FIFO working in both scenarios, which is why I think my comment appears ambiguous with the one on 431.  I am alluding to the fact that it is possible, just not practical.  I hope this is helpful in answering the question.  Let me know, I remain open for discussion.

**Comment by tmurfet** [comment]
I agree: "something which Azure Queues does not support **by default**" removes the ambiguity.

**Comment by benperk** [comment]
I will close this one out and get it updated ASAP.
