### ISSUE TITLE
Pg. 610 question # 4, answer A appears to be incorrect.

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#6]
Pg. 610 question # 4, answer A appears to be incorrect. There is no such tool as _Database Management Assistant (DMA)_ --> there is however, a _Database Migration Assistant (DMA)_.

**Comment by benperk** [comment]
This looks like a name change, because there was a feature called Database Management Assistant (DMA) which does the same as the Database Migration Assistant (DMA).  I agree that the current name is Database Migration Assistant (DMA).  I will get the question updated, as well as the discussion about DMA starting on page 559.  With that noted, the answer on page 689 for this questions is correct, in that, only D is not a correct answer, A, B and C are valid.
