### ISSUE TITLE
various typos

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#7]
I've identified typos by preceding the incorrect text with a quote including the correctly spelled word:
************
 1. pg. 275 2nd para., beneath fig. 4.24. :  _alteration_  | ...VM is a significant _altercation_.  ...
 2. pg. 283 1st para. 2nd line : _drop-down_ | ... The managed disk types in the table should be familiar to you; they were the options in the _drop-drop_ list for the OS disk type on the Disk tab when creating an Azure VM in the portal. ...
 3. pg. 339 1st para. : _deprecated_ | .. There was a product before AKS named Azure Container Service (ACS) that is being _depreciated_ and replaced by AKS. ...
 4. pg. 546 1st para. : _Lift and shift_ | _Life and shift_ can go directly to PaaS in many cases, and there are real benefits to doing so, such as autoscaling no longer being required for load balancing and delegating the responsibility for the management of operating systems and software libraries.
 5. pg. 547 1st para. :  _Cloudyn_ | ... The other way to optimize is by using Azure Cost Management and _Cloudy_, both of which were introduced in Chapter 1. ... (additionally: the Cloudyn product is deprecated at the end of 2020, so there ought not to have been any mention of it in this document. It's also mentioned in Chapter 1. To reduce confusion, IMO, it should be removed.
 6. pg. 549 3rd para. : _BCDR_ | ... The configuration of a _BDCR_ is relatively complicated ... (additionally:  the typo error is repeated twice more in the 1st para.)
 7. pg. 550 1st para. : _Azure Migrate_ | Also, you can recognize the complexities behind the logic that would help very much in scenarios where _Azure Monitor_ doesn’t provide a migration path for you. (additionally:  I'm sure that _Azure Monitor_ should read as _Azure Migrate_. The same error appears in the last para. on pg. 550).
 8. pg. 615, 2nd para. : _Mitch Radcliffe_ | _Mitch Radcliff_ is spelled incorrectly, it's actually Mitch Radcliffe with an "e". The quote is incomplete as well, the quote is actually: "A computer lets you make more mistakes faster than any other invention in human history -- with the possible exceptions of handguns and Tequila."
 9. pg. 640, last para. : _enhancements_ | Some of those _enchantments_ cannot be added to Azure VM metrics due to compatibilities, which is the reason for the differences.

**Comment by benperk** [comment]
Firstly, I really appreciate this.  I do want the book to be easy to read and for it to flow well.  Spelling mistakes impact the train of thought.  Thank you for bringing these to my attention and helping achieve this objective.

1. Agreed and in process of being corrected.
2. Agreed and in process of being corrected.
3. Agreed and in process of being corrected.  This is on page 338.
4. I have consistently wrote 'lift and shift' in lower case, in that example I use upper case for Lift because it is the first letter in the sentence.
5. Agreed and in process of being corrected.
6. Agreed and in process of being corrected.
7. Agreed and in process of being corrected.
8. Agreed and in process of being corrected.  I don't recall making a cognizant decision to leave the last part out, but I tend to agree with it.
9. Agreed and in process of being corrected.

Thanks again for the feedback.
