### ISSUE TITLE
pg. 109 question no. 8 The answer provided on page 684 is B, yet the answer text describes answer A.

### ISSUE THREAD

**Issue by tmurfet** [benperk/ASA#9]
pg. 109 question no. 8 The answer provided on page 684 is B, yet the answer text describes answer A. I believe that the correct provided answer should be A. Reference: pg. 101 para.: "Data in use"

**Comment by benperk** [comment]
I see your point.  The question is "which of the following is **false** about data-in-use encryption".  The answer should be C.  Computations on data that is stored within an enclave are performed in plaintext.  Answer A is a tricky one because I include the word "_all_ data while stored in memory".  The features of Azure Confidential Computing (ACC) and Trusted Execution Environments (TEE) are the ones which are in scope for this question.  In that context, only the data stored in the allocated memory enclave will be encrypted, not _all_ of it.  I recognize the ambiguity of this question and will work to improve it.  I will get the answer on page 684 to reflect C and get the description updated to better explain.
